### ISSUE TITLE
small mistake

### ISSUE THREAD

**Issue by DiagProf** [SquareBracketAssociates/Booklet-ConcurrentProgramming#2]
3.3 Understanding yield
...
..
.
4. P2 is active, it writes 10 and send the messageyield. // I think 11 is the right value for the example

**Comment by Ducasse** [comment]
Thanks ah yes :) I will name the processes also to be clearer.

**Comment by Ducasse** [comment]
Fixed. 
I got a lot of feedback from guillermo on the order of the material so I will produce a new version tomorrow.
