### ISSUE TITLE
Semapharo    too much Pharo :-)

### ISSUE THREAD

**Issue by DiagProf** [SquareBracketAssociates/Booklet-ConcurrentProgramming#5]
A great book
proposes different synchronization challenges that are solves with Semapharo: // <- really pharo?
The Little Book of Semaphores. It is clearly a nice further readings.

**Comment by Ducasse** [comment]
:)
Yes I do not know if I added a reference to it but I will. 
I'm still fighting a bit with some details around signalling.

**Comment by DiagProf** [comment]
Now is change from "Semapharo"  to  "Semaphare". I think it should be "Semaphores"

**Comment by Ducasse** [comment]
Thanks... geesh I would like to be able to work without getting interrupted :)
